<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>JetBrains.ReSharper.Azure.Psi</RootNamespace>
        <AssemblyName>JetBrains.ReSharper.Azure.Psi</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Azure.Project\Azure.Project.csproj" />
    </ItemGroup>

    <Import Project="$(JetBrainsRiderRdBackendCommonReference)" Condition="Exists('$(JetBrainsRiderRdBackendCommonReference)')" />

</Project>
