<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>JetBrains.ReSharper.Azure.Intellisense</RootNamespace>
        <AssemblyName>JetBrains.ReSharper.Azure.Intellisense</AssemblyName>
    </PropertyGroup>

    <Import Project="$(JetBrainsRiderRdBackendCommonReference)" Condition="Exists('$(JetBrainsRiderRdBackendCommonReference)')" />

    <ItemGroup>
        <PackageReference Include="CitizenMatt.ReSharper.LiveTemplateCompiler" Version="3.7.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Label="Live templates">
        <LiveTemplate Include="Templates\**\*.md">
            <OutputFile>Templates\templates.generated.dotSettings</OutputFile>
            <ReadmeFile>Templates\README.md</ReadmeFile>
        </LiveTemplate>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Azure.Project\Azure.Project.csproj" />
      <ProjectReference Include="..\Azure.Psi\Azure.Psi.csproj" />
    </ItemGroup>

</Project>
